/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpusar;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRClassLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author lenovo
 */
public class LaporanDataAnggota extends javax.swing.JFrame {
   public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    koneksi koneksi=new koneksi();
JasperReport jasperreport;
    JasperPrint jasperprint;
    JasperDesign jasperdesign;
    Map<String, Object> parameter = new HashMap<>();
    /**
     * Creates new form LaporanDataAnggota
     */
    public LaporanDataAnggota() {
        initComponents();
             
        setLocationRelativeTo(null);
        koneksi db = new koneksi();
        db.getConnection();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 530, 100));

        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jButton1.setText("PRINT");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID ANGGOA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 30));

        jButton3.setText("CARI MAMANG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, 30));

        jLabel2.setText("ID ANGGOTA 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });
        jPanel1.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 240, 30));

        jButton4.setText("CARI MAMANG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 30));

        jButton2.setText("CETAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel3.setText("ID Anggota");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        id2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                id2CaretUpdate(evt);
            }
        });
        id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id2ActionPerformed(evt);
            }
        });
        jPanel1.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 230, 30));

        jButton7.setText("CARI MAMANG");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 410, 230));

        jButton6.setText("CETAK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

 
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("Nama Anggota");
        tabelmapel.addColumn("ID Anggota");
        tabelmapel.addColumn("Status Anggota");
        tabelmapel.addColumn("Alamat");
        tabelmapel.addColumn("Tanggal Pembuatan ID");
        tabelmapel.addColumn("Nomor HP");
        tabelmapel.addColumn("Gender");
        tabelmapel.addColumn("E-Mail");
        try {
             sql = "select * from anggota where id_anggota ='"+id.getText()+"'";
               stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("id_anggota");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("status");
                o[3] = rs.getString("alamat");
                o[4] = rs.getString("tpid");
                o[5] = rs.getString("no_hp");
                o[6] = rs.getString("gender");
                o[7] = rs.getString("email");
                
                
            
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String a =id.getText();
            HashMap param = new HashMap();
            param.put("LaporanAnggota",a);

            File file = new File("src/report/LaporanAnggota.jrxml");
            System.out.print(1);
            jasperdesign = JRXmlLoader.load(file);
            parameter.clear();
            System.out.print(2);

            jasperreport=JasperCompileManager.compileReport(jasperdesign);
            System.out.print(3);

            jasperprint=JasperFillManager.fillReport(jasperreport, param, koneksi.getConnection());
            JasperViewer.viewReport(jasperprint,false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String transaksi = id1.getText();  // TODO add your handling code here:
         try{
        
String sql="select * from anggota where "+ "id_anggota='" +
        id1.getText()
+"'";
 rs = stat.executeQuery(sql);
       if (rs.next()){
   jTextArea1.setText("\n=========DATA ANGGOTA==============" + "\n"
                    + " ID ANGGOTA     : \" + rs.getString(1)+\"\\n\"\n" +
"                    + \"NAMA       : \" + rs.getString(2)+ \"\\n\"\n" +
"                    + \"STATUS      : \" + rs.getString(3)+ \"\\n\"\n" +
"                    + \"ALAMAT                 : \" + rs.getString(4)+ \"\\n\"\n" +
"                    + \"TANGGAAL BUAT ID                : \" + rs.getString(5) +\"\\n\"\n" +
"                    + \"NOMOR HP         : \" + rs.getString(6) +\"\\n\"\n" +
"                    + \"GENDER        : \" + rs.getString(7) +\"\\n\"\n" +
"                    + \"EMAIL         : \" + rs.getString(8) +\"\\n\"\n" +
"                    + \"Foto    : " + rs.getString(9) +"\n"
        
                    +

                    "\n============================================"+"\n");
            }else{
                
                jTextArea1.setText("");
                id1.setText("");
                stat.close();
                con.close();
            }
        }catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String transaksi = id2.getText();  // TODO add your handling code here:
         try{
        
String sql="select * from anggota where "+ "id_anggota='" +
        id2.getText()
+"'";
 rs = stat.executeQuery(sql);
       if (rs.next()){
   jTextArea1.setText("\n=========DATA ANGGOTA==============" + "\n"
                    + "ID ANGGOTA          : " + rs.getString(1) +"\n"
                    + "NAMA ANGGOTA        : " + rs.getString(2) +"\n"
                    + "STATUS            : " + rs.getString(3) +"\n"
                    + "ALAMAT         : " + rs.getString(4) +"\n"
                    + "TANGGAL BUAT ID   : " + rs.getString(5) +"\n"
                    + "NO HP        : " + rs.getString(6) +"\n"
                    + "GENDER    : " + rs.getString(7) +"\n"
                    + "EMAIL            : " + rs.getString(8) +"\n"
                    + "FOTO             : " + rs.getString(9) +"\n"+
                 "\n============================================"+"\n");
            }else{
                
                jTextArea1.setText("");
                id2.setText("");
                stat.close();
                con.close();
            }
        }catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    
      try {
    
          jTextArea1.print();
          jTextArea1.setText("");
          id2.setText("");

        } catch (Exception e) {
            dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
 int tabel=jTable1.getSelectedRow();
 String a=jTable1.getValueAt(tabel, 0).toString();
 id2.setText(a);
 
 try {
          sql="Select * from anggota";
               rs=stat.executeQuery(sql);
            while (rs.next()) {
         
                id2.setText(rs.getString(a));
        
         
        
          
         
            }
        }
        catch (Exception x) {
             
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void id2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_id2CaretUpdate
        // TODO add your handling code here:
         String transaksi = id2.getText();  // TODO add your handling code here:
         try{
        
String sql="select * from anggota where "+ "id_anggota='" +
        id2.getText()
+"'";
 rs = stat.executeQuery(sql);
       if (rs.next()){
   jTextArea1.setText("\n=========DATA ANGGOTA==============" + "\n"
                    + "ID ANGGOTA          : " + rs.getString(1) +"\n"
                    + "NAMA ANGGOTA        : " + rs.getString(2) +"\n"
                    + "STATUS            : " + rs.getString(3) +"\n"
                    + "ALAMAT         : " + rs.getString(4) +"\n"
                    + "TANGGAL BUAT ID   : " + rs.getString(5) +"\n"
                    + "NO HP        : " + rs.getString(6) +"\n"
                    + "GENDER    : " + rs.getString(7) +"\n"
                    + "EMAIL            : " + rs.getString(8) +"\n"
                    + "FOTO             : " + rs.getString(9) +"\n"+
                 "\n============================================"+"\n");
            }else{
                
                jTextArea1.setText("");
                id2.setText("");
                stat.close();
                con.close();
            }
        }catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
        }

    
    }//GEN-LAST:event_id2CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanDataAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JTextField id1;
    private javax.swing.JTextField id2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    

   private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("ID ANGGOTA");
        tabelmapel.addColumn("Nama Anggota");
        tabelmapel.addColumn("Status Anggota");
        tabelmapel.addColumn("Alamat");
        tabelmapel.addColumn("Tanggal Pembuatan ID");
        tabelmapel.addColumn("Nomor HP");
        tabelmapel.addColumn("Gender");
        tabelmapel.addColumn("E-Mail");
        try {
             sql = "select * from anggota";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("id_anggota");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("status");
                o[3] = rs.getString("alamat");
                o[4] = rs.getString("tpid");
                o[5] = rs.getString("no_hp");
                o[6] = rs.getString("gender");
                o[7] = rs.getString("email");
                
            
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }

 


}
