/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryar;
 
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRClassLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
/**

/**
 *
 * @author lenovo
 */
public class FormSepatu extends javax.swing.JFrame {
public String tglkir="";
public String tgljem="";
 public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    
    
    koneksi koneksi=new koneksi();
JasperReport jasperreport;
    JasperPrint jasperprint;
    JasperDesign jasperdesign;
    Map<String, Object> param = new HashMap<>();
    /**
     * Creates new form 
     */
    public FormSepatu() {
        
        initComponents();
          setLocationRelativeTo(null);
        koneksi db = new koneksi();
        db.getConnection();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
        idauto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nama_sepatu = new javax.swing.JTextField();
        jenissepatu = new javax.swing.JTextField();
        banyak = new javax.swing.JTextField();
        letak = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tglkirim = new com.toedter.calendar.JDateChooser();
        tgljemput = new com.toedter.calendar.JDateChooser();
        image = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PENDATAAN SEPATU MASUK LAUNDRY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID SEPATU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA SEPATU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS SEPATU");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BANYAK SEPATU");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TGL KIRIM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TGL JEMPUT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LETAK RAK SEPATU");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 260, 30));
        jPanel1.add(nama_sepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 260, 30));
        jPanel1.add(jenissepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 260, 30));
        jPanel1.add(banyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 70, 30));
        jPanel1.add(letak, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 260, 30));

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 490, 90));

        tglkirim.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglkirimPropertyChange(evt);
            }
        });
        jPanel1.add(tglkirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 30));

        tgljemput.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgljemputPropertyChange(evt);
            }
        });
        jPanel1.add(tgljemput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 260, 30));

        image.setText("Select Image");
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 150, 30));
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 240, 160));

        clear.setText("CLEAR");
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PASANG");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jButton4.setBackground(new java.awt.Color(84, 93, 102));
        jButton4.setText("Menu Utama");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void tglkirimPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglkirimPropertyChange
     
           // TODO add your handling code here:
          if (tglkirim.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            tglkir = String.valueOf(format.format(tglkirim.getDate()));
        }
                          
        
    }//GEN-LAST:event_tglkirimPropertyChange

    private void tgljemputPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgljemputPropertyChange
        // TODO add your handling code here:
        if (tgljemput.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            tgljem = String.valueOf(format.format(tgljemput.getDate()));
    }//GEN-LAST:event_tgljemputPropertyChange
}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
         try {
            sql = "insert sepatu values ('"
            + id.getText() + "','"
            + nama_sepatu.getText() + "','"
            + jenissepatu.getText() + "','"
            + banyak.getText() + "','"
            +    tglkir    + "','"
          
            + tgljem+ "','"
            + letak.getText()+"','"
            + foto.getText() +"')";
              
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data "+ id.getText()+" Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data "+ id.getText()+" Tidak Berhasil Disimpan"+e);
        }

        id.setText("");
        nama_sepatu.setText("");
        jenissepatu.setText("");
        banyak.setText("");
        tglkirim.setDate(null);

        tgljemput.setDate(null);
        letak.setText("");
     

        tampilkan_data();
                 idauto();
        
    }//GEN-LAST:event_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            int tabel=jTable1.getSelectedRow();
        String a=jTable1.getValueAt(tabel, 0).toString();
        String b=jTable1.getValueAt(tabel, 1).toString();
        String c=jTable1.getValueAt(tabel, 2).toString();
       
        String g=jTable1.getValueAt(tabel, 3).toString();
      
       
       String l=jTable1.getValueAt(tabel, 6).toString();
        
         try {
            String s =(String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4);
            String k =(String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5);
            SimpleDateFormat f = new SimpleDateFormat("yyyy-M-dd");
            java.util.Date d = f.parse(s);
            java.util.Date h = f.parse(k);
            tglkirim.setDate(d);
            tgljemput.setDate(h);
        } catch (Exception e) {

        }
        
        id.setText(a);
        nama_sepatu.setText(b);
        jenissepatu.setText(c);
        banyak.setText(g);
       
        letak.setText(l);
    
        
        try {
          sql="Select * from sepatu";
               rs=stat.executeQuery(sql);
            while (rs.next()) {
         
                id.setText(rs.getString(a));
                nama_sepatu.setText(rs.getString(b));
                jenissepatu.setText(rs.getString(c));   
                banyak.setText(rs.getString(g));  
                letak.setText(rs.getString(l)); 
             
         
        
          
         
            }
        }
        catch (Exception x) {
             
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         
        try {
            sql="update sepatu set nama_sepatu='"+nama_sepatu.getText()
                    +"',jenis_sepatu='"+jenissepatu.getText()
                    +"',banyak_sepatu='"+banyak.getText()
                    +"',tgl_kirim='"+tglkir
                    +"',tgl_jemput='"+tgljem
                    +"',letak='"+letak.getText()
                    +"',foto='"+foto.getText()
                    +"'where id_sepatu='"+id.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data " + id.getText() + "" + " Telah Di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + id.getText() + "" + " Belum Di Edit"+e);
        }

        id.setText("");

       tglkirim.setDate(null);
       
       tgljemput.setDate(null);
       
       banyak.setText("");

 

        letak.setText("");

        jenissepatu.setText("");
        
        nama_sepatu.setText("");
        
       
        
       
              tampilkan_data();
              idauto();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        try {
            sql = "delete from sepatu where id_sepatu='" + id.getText() + "'";
            stat = con.createStatement();
            stat.executeUpdate(sql);
            stat.close();
            JOptionPane.showMessageDialog(null, "Data " + id.getText() + "" + " Telah Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " +id.getText() + "" + " Belum Dihapus");
        }
        
        id.setText("");

        nama_sepatu.setText("");
     
        tglkirim.setDate(null);
        tgljemput.setDate(null);


        banyak.setText("");

        letak.setText("");

        jenissepatu.setText("");
   
        
         
   tampilkan_data();
                    idauto();                   

    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        // TODO add your handling code here:
        //        JFileChooser chooser = new JFileChooser();
        //chooser.showOpenDialog(null);
        //File f= chooser.getSelectedFile();
        //        filename = f.getAbsolutePath();
        //        ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(foto.getWidth(),foto.getHeight(),Image.SCALE_SMOOTH ));
        //        foto.setIcon(imageicon);

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
    String filename = f.getAbsolutePath();
        ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(foto.getWidth(),foto.getHeight(),Image.SCALE_SMOOTH ));
        foto.setText(filename);
        foto.setIcon(imageicon);

        try {
            File image= new File (filename);
            FileInputStream fis= new FileInputStream(image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte [1024];
            for(int readNum; (readNum=fis.read(buf)) !=-1;){

                bos.write(buf, 0, readNum);
                Icon ImageIcon = null;

            }
            byte[] person_image = bos.toByteArray();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_imageActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new MenuUtama().show();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSepatu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField banyak;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel foto;
    private javax.swing.JTextField id;
    private javax.swing.JButton image;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jenissepatu;
    private javax.swing.JTextField letak;
    private javax.swing.JTextField nama_sepatu;
    private com.toedter.calendar.JDateChooser tgljemput;
    private com.toedter.calendar.JDateChooser tglkirim;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables


    private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("ID SEPATU");
        tabelmapel.addColumn("Nama Sepatu");
        tabelmapel.addColumn("Jenis Sepatu");
        tabelmapel.addColumn("Banyak Sepatu");
        tabelmapel.addColumn("Tgl Kirim");
       
        tabelmapel.addColumn("Tgl Jemput");
        tabelmapel.addColumn("Letak");
        tabelmapel.addColumn("Foto");
     
        try {
             sql = "select * from sepatu";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("id_sepatu");
                o[1] = rs.getString("nama_sepatu");
                o[2] = rs.getString("jenis_sepatu");
                o[3] = rs.getString("banyak_sepatu");
                o[4] = rs.getString("tgl_kirim");
                o[5] = rs.getString("tgl_jemput");
                o[6] = rs.getString("letak");
                o[7] = rs.getString("foto");
                 
             
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }

  
    
     }

private void idauto(){
           try{
    
    String sql="select right (id_sepatu,2) as id_sepatu from sepatu";
    Statement stat=con.createStatement();
    ResultSet rs=stat.executeQuery(sql);
    if(rs.first()==false){
       
    }else{ 
        rs.last(); 
        int no=rs.getInt(1)+1;
        String cno=String.valueOf(no);
        int pjg_cno=cno.length();
        for(int i=0;i<2-pjg_cno;i++){
         
    
}
        
    id.setText("SP00"+cno);
        
    }
}catch(Exception e ){
}
}

}
