/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryar;

import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author Ghulam Zaky
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    
     public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
     }
   
    
    
   public MenuUtama(String userakses) {
       initComponents();
        setLocationRelativeTo(this);
      
        if (userakses.equals("admin")) {
         master.setEnabled(true);
         entrisepatu.setEnabled(true);
         entriclient.setEnabled(true);
       
        }
      
        else if(userakses.equals("user")){
         master.setEnabled(true);
         entrisepatu.setEnabled(false);
         entriclient.setEnabled(true);
        
        }
   
    
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIF = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        entrisepatu = new javax.swing.JMenuItem();
        entriclient = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIF.setVisible(true);
        jIF.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2.jpg"))); // NOI18N
        jIF.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        getContentPane().add(jIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 490));

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_Key_32495.png"))); // NOI18N
        jMenu4.setText("LOGIN  |");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_user_male2_172626.png"))); // NOI18N
        jMenuItem3.setText("FORM LOGIN");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_Open_1493293.png"))); // NOI18N
        master.setText(" MASTER DATA   |");

        entrisepatu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_Food_C226_2427886.png"))); // NOI18N
        entrisepatu.setText("ENTRI DATA SEPATU");
        entrisepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrisepatuActionPerformed(evt);
            }
        });
        master.add(entrisepatu);

        entriclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_property-agent-004_1851813.png"))); // NOI18N
        entriclient.setText("ENTRI DATA CLIENT");
        entriclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriclientActionPerformed(evt);
            }
        });
        master.add(entriclient);

        jMenuBar2.add(master);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_Open_1493293.png"))); // NOI18N
        jMenu1.setText("TRANSAKSI PENJUALAN");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_floppy_285657.png"))); // NOI18N
        jMenuItem5.setText("DATA PENJUALAN");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar2.add(jMenu1);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_Cancel_1493282.png"))); // NOI18N
        jMenu6.setText("KELUAR   |");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrisepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrisepatuActionPerformed
   
new FormSepatu().show();
    }//GEN-LAST:event_entrisepatuActionPerformed

    private void entriclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriclientActionPerformed
        // TODO add your handling code here:
        new FormClient().show();
    }//GEN-LAST:event_entriclientActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem entriclient;
    private javax.swing.JMenuItem entrisepatu;
    private javax.swing.JInternalFrame jIF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu master;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    
    private void setting() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    private void belumlogin(){
       
    }
    
    private void admin(){
       master.setVisible(false);
    }
    
    private void user(){
        
    }
}
