/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpusar;
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRClassLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrator
 */
public class FormPinjam extends javax.swing.JFrame {
public String tglpin="";
public String deadline="";
 public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    koneksi koneksi=new koneksi();
JasperReport jasperreport;
    JasperPrint jasperprint;
    JasperDesign jasperdesign;
    Map<String, Object> param = new HashMap<>();
    /**
     * Creates new form FormPinjam
     */
    public FormPinjam() {
        initComponents();
              setLocationRelativeTo(null);
        koneksi db = new koneksi();
        db.getConnection();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idpen = new javax.swing.JTextField();
        idbuku = new javax.swing.JTextField();
        petugas = new javax.swing.JTextField();
        idanggota = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        dead = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        status = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID PINJAM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID BUKU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID ANGGOTA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TANGGAL PINJAM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEADLINE PINJAM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PETUGAS ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        jPanel1.add(idpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 340, 30));
        jPanel1.add(idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 340, 30));
        jPanel1.add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 340, 30));
        jPanel1.add(idanggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 340, 30));

        tglpinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglpinjamPropertyChange(evt);
            }
        });
        jPanel1.add(tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 340, 30));

        dead.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                deadPropertyChange(evt);
            }
        });
        jPanel1.add(dead, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 340, 30));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FORM PINJAM BUKU PERPUSTAKAAN AR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 500, 60));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jButton4.setText("CLEAR");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 490, 100));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 340, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STATUS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jButton5.setText("CETAK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hero-product-pages.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglpinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglpinjamPropertyChange

        // TODO add your handling code here:
        if (tglpinjam.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            tglpin = String.valueOf(format.format(tglpinjam.getDate()));
        }

    }//GEN-LAST:event_tglpinjamPropertyChange

    private void deadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_deadPropertyChange
        // TODO add your handling code here:
        if (dead.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            deadline = String.valueOf(format.format(dead.getDate()));
    }//GEN-LAST:event_deadPropertyChange
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             
        try {
            sql = "insert into pinjam values ('"
            + idpen.getText() + "','"
            + idbuku.getText() + "','"
            + idanggota.getText() + "','"
            + status.getText() + "','"
            +    tglpin    + "','"
            +    deadline    + "','" 
            + petugas.getText()+"')";
              
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data "+ idpen.getText()+" Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data "+ idpen.getText()+" Tidak Berhasil Disimpan"+e);
        }

        idpen.setText("");
        idbuku.setText("");
        idanggota.setText("");
        status.setText("");
        tglpinjam.setDate(null);
        dead.setDate(null);
        petugas.setText("");
       tampilkan_data();
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int tabel=jTable1.getSelectedRow();
        String idpeminjam=jTable1.getValueAt(tabel, 0).toString();
        String idbukuu=jTable1.getValueAt(tabel, 1).toString();
        String idanggotaa=jTable1.getValueAt(tabel, 2).toString();
       
        String statuss=jTable1.getValueAt(tabel, 3).toString();
        String petugass=jTable1.getValueAt(tabel, 6).toString();
      
         try {
            String tglpin =(String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4);
            String deadline =(String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5);
            SimpleDateFormat f = new SimpleDateFormat("yyyy-M-dd");
            java.util.Date d = f.parse(tglpin);
            java.util.Date h = f.parse(deadline);
            tglpinjam.setDate(d);
            dead.setDate(h);
        } catch (Exception e) {

        }
        
        idpen.setText(idpeminjam);
        idbuku.setText(idbukuu);
        idanggota.setText(idanggotaa);
        petugas.setText(petugass);
        status.setText(statuss);
      
    
        
        try {
          sql="Select * from buku";
               rs=stat.executeQuery(sql);
            while (rs.next()) {
         
                idpen.setText(rs.getString(idpeminjam));
                idanggota.setText(rs.getString(idanggotaa));
                idbuku.setText(rs.getString(idbukuu));   
                petugas.setText(rs.getString(petugass));  
                status.setText(rs.getString(statuss));  
         
        
          
         
            }
        }
        catch (Exception x) {
             
        }
                                  
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
            sql="update pinjam set id_pinjam='"+idpen.getText()
                    +"',id_buku='"+idbuku.getText()
                    +"',id_anggota='"+idanggota.getText()
                    +"',status='"+status.getText()
                    +"',tglpinjam='"+tglpin
                    +"',tglkembali='"+deadline
                    +"',petugas='"+petugas.getText()+"'";
            
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data " + idpen.getText() + "" + " Telah Di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + idpen.getText() + "" + " Belum Di Edit"+e);
        }

        idpen.setText("");

       tglpinjam.setDate(null);
       
       dead.setDate(null);
       
       idanggota.setText("");

        idbuku.setText("");

        petugas.setText("");
        
        tampilkan_data();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      try {
            sql = "delete from pinjam where id_pinjam='" + idpen.getText() + "'";
            stat = con.createStatement();
            stat.executeUpdate(sql);
            stat.close();
            JOptionPane.showMessageDialog(null, "Data " + idpen.getText() + "" + " Telah Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " +idpen.getText() + "" + " Belum Dihapus");
        }
        
        idpen.setText("");

        idanggota.setText("");
        
        status.setText("");
     
        tglpinjam.setDate(null);
        dead.setDate(null);

        petugas.setText("");

        idbuku.setText("");
        
        tampilkan_data();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try{
            java.io.File file = new java.io.File 
                    ("src/report/LaporanStaff.jrxml");
            jasperdesign = JRXmlLoader.load(file);
            param.clear();
            jasperreport=JasperCompileManager.compileReport(jasperdesign);
            jasperprint=JasperFillManager.fillReport(jasperreport, param, koneksi.getConnection());
            JasperViewer.viewReport(jasperprint,false);
        } catch (Exception e) {
     
     }
    
        
    }//GEN-LAST:event_jButton5ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dead;
    private javax.swing.JTextField idanggota;
    private javax.swing.JTextField idbuku;
    private javax.swing.JTextField idpen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField petugas;
    private javax.swing.JTextField status;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables

 private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("ID PEMINJAM");
        tabelmapel.addColumn("ID BUKU");
        tabelmapel.addColumn("ID ANGGOTA");
        tabelmapel.addColumn("STATUS");
        tabelmapel.addColumn("TGL PINJAM");
        tabelmapel.addColumn("TGL KEMBALI");
        tabelmapel.addColumn("PETUGAS");
      
     
        try {
             sql = "select * from pinjam";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[7];
                o[0] = rs.getString("id_pinjam");
                o[1] = rs.getString("id_buku");
                o[2] = rs.getString("id_anggota");
                o[3] = rs.getString("status");
                o[4] = rs.getString("tglpinjam");
                o[5] = rs.getString("tglkembali");
                o[6] = rs.getString("petugas");
               
             
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }

  
    
     }


}




