/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package perpusar;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRClassLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author lenovo
 */
public class LaporanDataBuku extends javax.swing.JFrame {
     public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    koneksi koneksi=new koneksi();
JasperReport jasperreport;
    JasperPrint jasperprint;
    JasperDesign jasperdesign;
    Map<String, Object> parameter = new HashMap<>();
    

    /** Creates new form LaporanDataBuku */
    public LaporanDataBuku() {
         initComponents();
              
        setLocationRelativeTo(null);
        koneksi db = new koneksi();
        db.getConnection();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idbuku = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idd = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 530, 100));

        jButton1.setText("PRINT");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jButton2.setText("CETAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel1.setText("ID BUKU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbukuActionPerformed(evt);
            }
        });
        jPanel1.add(idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, 30));

        jButton3.setText("CARI MAMANG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 30));

        jLabel2.setText("ID Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        idd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                iddCaretUpdate(evt);
            }
        });
        idd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddActionPerformed(evt);
            }
        });
        jPanel1.add(idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 230, 30));

        jButton4.setText("CARI MAMANG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, -1, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 410, 230));

        jButton6.setText("CETAK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void idbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbukuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("ID Buku");
        tabelmapel.addColumn("Nama Buku");
        tabelmapel.addColumn("Genre Buku");
        tabelmapel.addColumn("Nama Penulis");
        tabelmapel.addColumn("Tgl Terbit");
        tabelmapel.addColumn("Penerbit");
        tabelmapel.addColumn("Tgl Masuk");
        tabelmapel.addColumn("Letak");
        tabelmapel.addColumn("Foto");
     
        try {
             sql = "select * from buku where id_buku='"+idbuku.getText()+"'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("id_buku");
                o[1] = rs.getString("nama_buku");
                o[2] = rs.getString("genre");
                o[3] = rs.getString("penulis");
                o[4] = rs.getString("terbit");
                o[5] = rs.getString("penerbit");
                o[6] = rs.getString("masuk");
                o[7] = rs.getString("letak");
                 o[8] = rs.getString("foto");
             
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }

  
    
     

  
    
     

        
        
        
        
        
        
       

  
    
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            try{
                String a =idbuku.getText();
                HashMap param = new HashMap();
                param.put("laporanbuku",a);
                        
            File file = new File("src/report/LaporanBuku.jrxml");
            System.out.print(1);
            jasperdesign = JRXmlLoader.load(file);
            parameter.clear();
                        System.out.print(2);

            jasperreport=JasperCompileManager.compileReport(jasperdesign);
                        System.out.print(3);

            jasperprint=JasperFillManager.fillReport(jasperreport, param, koneksi.getConnection());
            JasperViewer.viewReport(jasperprint,false);
        } catch (Exception e) {
     
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void iddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String transaksi = idd.getText();  // TODO add your handling code here:
         try{
        
String sql="select * from buku where "+ "id_buku='" +
        idd.getText()
+"'";
 rs = stat.executeQuery(sql);
       if (rs.next()){
   jTextArea1.setText("\n=========DATA BUKU==============" + "\n"
                    + "ID BUKU          : " + rs.getString(1) +"\n"
                    + "NAMA BUKU        : " + rs.getString(2) +"\n"
                    + "GENRE            : " + rs.getString(3) +"\n"
                    + "PENULIS          : " + rs.getString(4) +"\n"
                    + "TANGGAL TERBIT   : " + rs.getString(5) +"\n"
                    + "PENERBIT         : " + rs.getString(6) +"\n"
                    + "TANGGAL MASUK    : " + rs.getString(7) +"\n"
                    + "LETAK            : " + rs.getString(8) +"\n"
                    + "FOTO             : " + rs.getString(9) +"\n"+
                 "\n============================================"+"\n");
            }else{
                
                jTextArea1.setText("");
                idd.setText("");
                stat.close();
                con.close();
            }
        }catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

      try {
          jTextArea1.print();
          jTextArea1.setText("");
          idd.setText("");

        } catch (Exception e) {
            dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void iddCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_iddCaretUpdate
        // TODO add your handling code here:
        String transaksi = idd.getText();  // TODO add your handling code here:
         try{
        
String sql="select * from buku where "+ "id_buku='" +
        idd.getText()
+"'";
 rs = stat.executeQuery(sql);
       if (rs.next()){
   jTextArea1.setText("\n=========DATA BUKU==============" + "\n"
                    + "ID BUKU          : " + rs.getString(1) +"\n"
                    + "NAMA BUKU        : " + rs.getString(2) +"\n"
                    + "GENRE            : " + rs.getString(3) +"\n"
                    + "PENULIS          : " + rs.getString(4) +"\n"
                    + "TANGGAL TERBIT   : " + rs.getString(5) +"\n"
                    + "PENERBIT         : " + rs.getString(6) +"\n"
                    + "TANGGAL MASUK    : " + rs.getString(7) +"\n"
                    + "LETAK            : " + rs.getString(8) +"\n"
                    + "FOTO             : " + rs.getString(9) +"\n"+
                 "\n============================================"+"\n");
            }else{
                
                jTextArea1.setText("");
                idd.setText("");
                stat.close();
                con.close();
            }
        }catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
        }

        
    }//GEN-LAST:event_iddCaretUpdate

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                int tabel=jTable1.getSelectedRow();
 String a=jTable1.getValueAt(tabel, 0).toString();
 idd.setText(a);
 
 try {
          sql="Select * from buku";
               rs=stat.executeQuery(sql);
            while (rs.next()) {
         
                idd.setText(rs.getString(a));
        
         
        
          
         
            }
        }
        catch (Exception x) {
             
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanDataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanDataBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idbuku;
    private javax.swing.JTextField idd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    
       private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("ID Buku");
        tabelmapel.addColumn("Nama Buku");
        tabelmapel.addColumn("Genre Buku");
        tabelmapel.addColumn("Nama Penulis");
        tabelmapel.addColumn("Tgl Terbit");
        tabelmapel.addColumn("Penerbit");
        tabelmapel.addColumn("Tgl Masuk");
        tabelmapel.addColumn("Letak");
        tabelmapel.addColumn("Foto");
     
        try {
             sql = "select * from buku";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("id_buku");
                o[1] = rs.getString("nama_buku");
                o[2] = rs.getString("genre");
                o[3] = rs.getString("penulis");
                o[4] = rs.getString("terbit");
                o[5] = rs.getString("penerbit");
                o[6] = rs.getString("masuk");
                o[7] = rs.getString("letak");
                 o[8] = rs.getString("foto");
             
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }

  
    
     }

    
     
    
}
