/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Kel_4;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;
/**
 *
 * @author User
 */
public class admin extends javax.swing.JFrame {
public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    /**
     * Creates new form 
     */
    public admin() {
        initComponents();
        setLocationRelativeTo(null);
        koneksiDB db = new koneksiDB();
        db.koneksi();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        na = new javax.swing.JTextField();
        aa = new javax.swing.JTextField();
        ea = new javax.swing.JTextField();
        nha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nha1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        na.setToolTipText("");
        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });
        na.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                naKeyReleased(evt);
            }
        });
        getContentPane().add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 30));

        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });
        aa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aaKeyReleased(evt);
            }
        });
        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 30));

        ea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaActionPerformed(evt);
            }
        });
        ea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eaKeyReleased(evt);
            }
        });
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, 30));

        nha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaActionPerformed(evt);
            }
        });
        nha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nhaKeyReleased(evt);
            }
        });
        getContentPane().add(nha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 810, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALAMAT ADMIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAMA ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMAIL ADMIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMOR HP ADMIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        btSimpan.setBackground(new java.awt.Color(84, 93, 102));
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-save-as.png"))); // NOI18N
        btSimpan.setText("SIMPAN");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, -1));

        btEdit.setBackground(new java.awt.Color(84, 93, 102));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-edit.png"))); // NOI18N
        btEdit.setText("EDIT");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 100, -1));

        btDelete.setBackground(new java.awt.Color(84, 93, 102));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/document_delete.png"))); // NOI18N
        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 100, -1));

        btBatal.setBackground(new java.awt.Color(84, 93, 102));
        btBatal.setText("CLEAR");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 100, 30));

        btKeluar.setBackground(new java.awt.Color(84, 93, 102));
        btKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/1382877036_Exit.png"))); // NOI18N
        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 340, -1));

        jButton1.setBackground(new java.awt.Color(84, 93, 102));
        jButton1.setText("Menu Utama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 800, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SHIFT ADMIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        nha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nha1ActionPerformed(evt);
            }
        });
        nha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nha1KeyReleased(evt);
            }
        });
        getContentPane().add(nha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/bg3.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 440));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void naActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naActionPerformed

        try {
            sql = "select * from tbladmin where namaadmin='" + na.getText() + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                aa.setText(rs.getString("namaadmin"));
                ea.setText(rs.getString("email"));
                nha.setText(rs.getString("nohp"));
                nha1.setText(rs.getString(5));

                JOptionPane.showMessageDialog(null, "Ini Data " + na.getText() + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_naActionPerformed

    private void naKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_naKeyReleased

        if (evt.getKeyCode() == 10) {
            aa.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_naKeyReleased

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aaActionPerformed

    private void aaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aaKeyReleased

        if (evt.getKeyCode() == 10) {
            ea.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_aaKeyReleased

    private void eaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eaKeyReleased

        if (evt.getKeyCode() == 10) {
            nha.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_eaKeyReleased

    private void nhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhaActionPerformed

    private void nhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nhaKeyReleased

        if (evt.getKeyCode() == 10) {
            na.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_nhaKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        na.setText(jTable1.getValueAt
            (jTable1.getSelectedRow(), 0).toString());
        aa.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        ea.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        nha.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        nha1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed

        try {
            sql = "insert into  tbladmin values ('"
            + na.getText() + "','"
            + aa.getText() + "','"
            + ea.getText() + "','"
            + nha.getText() + "','"
            + nha1.getText() + "')";

            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data "+ na.getText()+" Berhasil Disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data "+ na.getText()+" Tidak Berhasil Disimpan"+e);
        }

        na.setText("");
        aa.setText("");
        ea.setText("");
        nha.setText("");
nha1.setText("");
        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed

        try {
            sql="update tbladmin set alamatadmin='"+
            aa.getText()+"',emailadmin='"+
            ea.getText()+"', nohp='"+
            nha.getText()+"', shift='"+
            nha1.getText()

            +"' where namaadmin='"+na.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data " + na.getText() + "" + " Telah Di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + na.getText() + "" + " Belum Di Edit"+e);
        }

        na.setText("");
        aa.setText("");
        ea.setText("");
        nha.setText("");
        nha1.setText("");
        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed

        try {
            sql = "delete from tbladmin where namaadmin='" + na.getText() + "'";
            stat = con.createStatement();
            stat.executeUpdate(sql);
            stat.close();
            JOptionPane.showMessageDialog(null, "Data " + na.getText() + "" + " Telah Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + na.getText() + "" + " Belum Dihapus");
        }

        na.setText("");
        aa.setText("");
        ea.setText("");
        nha.setText("");
        nha1.setText("");   

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed

        na.setText("");
        aa.setText("");
        ea.setText("");
        nha.setText("");
        nha1.setText("");

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btBatalActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btKeluarActionPerformed

    private void eaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaActionPerformed

    private void nha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nha1ActionPerformed

    private void nha1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nha1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nha1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuUtama().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("namaadmin");
        tabelmapel.addColumn("alamatadmin");
        tabelmapel.addColumn("emailadmin");
        tabelmapel.addColumn("nohp");
        tabelmapel.addColumn("shift");
        try {
             sql = "select * from tbladmin";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[5];
                o[0] = rs.getString("namaadmin");
                o[1] = rs.getString("alamatadmin");
                o[2] = rs.getString("emailadmin");
                o[3] = rs.getString("nohp");
                o[4] = rs.getString("shift");
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aa;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btSimpan;
    private javax.swing.JTextField ea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField na;
    private javax.swing.JTextField nha;
    private javax.swing.JTextField nha1;
    // End of variables declaration//GEN-END:variables
}
