/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Kel_4;

import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;

/**
 *
 * @author
 */
public class Inventory extends javax.swing.JFrame {

    public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    public String tgl = "";
    public String KodeBeras = "";
    Integer a, b, hasil;

    /**
     * Creates new form If_Then
     */
    public Inventory() {
        initComponents();
        setLocationRelativeTo(null);
        koneksiDB db = new koneksiDB();
        db.koneksi();
        con = db.con;
        stat = db.stat;
        tampilkan_data();

    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btKeluar = new javax.swing.JButton();
        btSimpan = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btProses = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKB = new javax.swing.JTextField();
        txtNB = new javax.swing.JTextField();
        txtS = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtJ = new javax.swing.JTextField();
        txtT = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        txtTH = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 58, 64));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("JUMLAH");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HARGA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA BERAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btKeluar.setBackground(new java.awt.Color(84, 93, 102));
        btKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/1382877036_Exit.png"))); // NOI18N
        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 370, -1));

        btSimpan.setBackground(new java.awt.Color(84, 93, 102));
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-save-as.png"))); // NOI18N
        btSimpan.setText("SIMPAN");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        btBatal.setBackground(new java.awt.Color(84, 93, 102));
        btBatal.setText("CLEAR");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 100, 36));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS BERAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btProses.setBackground(new java.awt.Color(84, 93, 102));
        btProses.setText("PROSES");
        btProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProsesActionPerformed(evt);
            }
        });
        btProses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btProsesKeyPressed(evt);
            }
        });
        getContentPane().add(btProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 80, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BONUS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btEdit.setBackground(new java.awt.Color(84, 93, 102));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-edit.png"))); // NOI18N
        btEdit.setText("EDIT");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 100, -1));

        btDelete.setBackground(new java.awt.Color(84, 93, 102));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/document_delete.png"))); // NOI18N
        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 820, 100));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE BERAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DISKON");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL HARGA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EXPIRED");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        txtKB.setToolTipText("");
        txtKB.setNextFocusableComponent(txtNB);
        txtKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKBActionPerformed(evt);
            }
        });
        txtKB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKBKeyReleased(evt);
            }
        });
        getContentPane().add(txtKB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, 30));
        txtKB.getAccessibleContext().setAccessibleName("");
        txtKB.getAccessibleContext().setAccessibleDescription("P000");

        txtNB.setNextFocusableComponent(txtS);
        txtNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNBActionPerformed(evt);
            }
        });
        txtNB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNBKeyReleased(evt);
            }
        });
        getContentPane().add(txtNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, 30));

        txtS.setNextFocusableComponent(txtH);
        txtS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSKeyReleased(evt);
            }
        });
        getContentPane().add(txtS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 30));

        txtH.setNextFocusableComponent(txtB);
        txtH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHActionPerformed(evt);
            }
        });
        txtH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHKeyReleased(evt);
            }
        });
        getContentPane().add(txtH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 140, 30));

        txtB.setNextFocusableComponent(txtJ);
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBKeyReleased(evt);
            }
        });
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 140, 30));

        txtJ.setNextFocusableComponent(btProses);
        txtJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJActionPerformed(evt);
            }
        });
        txtJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJKeyReleased(evt);
            }
        });
        getContentPane().add(txtJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 140, 30));

        txtT.setEditable(false);
        txtT.setBackground(new java.awt.Color(255, 255, 255));
        txtT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTActionPerformed(evt);
            }
        });
        getContentPane().add(txtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, 30));

        txtD.setEditable(false);
        txtD.setBackground(new java.awt.Color(255, 255, 255));
        txtD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDActionPerformed(evt);
            }
        });
        getContentPane().add(txtD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 140, 30));

        txtTH.setEditable(false);
        txtTH.setBackground(new java.awt.Color(255, 255, 255));
        txtTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTHActionPerformed(evt);
            }
        });
        getContentPane().add(txtTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 140, 30));

        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 140, 30));

        jLabel6.setBackground(new java.awt.Color(52, 58, 64));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/inven2.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 460, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRY DATA BERAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 310, -1));

        jButton1.setBackground(new java.awt.Color(84, 93, 102));
        jButton1.setText("Menu Utama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 820, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 2140, 990));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange

        if (date.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            tgl = String.valueOf(format.format(date.getDate()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_datePropertyChange

    private void txtTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTHActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTHActionPerformed

    private void txtDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDActionPerformed

    private void txtTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTActionPerformed

    private void txtJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJKeyReleased

        if (evt.getKeyCode() == 10) {
            btProses.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtJKeyReleased

    private void txtJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJActionPerformed

    private void txtBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyReleased

        if (evt.getKeyCode() == 10) {
            txtJ.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtBKeyReleased

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void txtHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHKeyReleased

        if (evt.getKeyCode() == 10) {
            txtB.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtHKeyReleased

    private void txtHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHActionPerformed

    private void txtSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSKeyReleased

        if (evt.getKeyCode() == 10) {
            txtH.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKeyReleased

    private void txtNBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNBKeyReleased

        if (evt.getKeyCode() == 10) {
            txtS.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNBKeyReleased

    private void txtNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNBActionPerformed

    private void txtKBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKBKeyReleased

        if (evt.getKeyCode() == 10) {
            txtNB.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtKBKeyReleased

    private void txtKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKBActionPerformed

        try {
            sql = "select * from tbbarang where KodeBeras='" + txtKB.getText() + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                txtNB.setText(rs.getString("NamaBeras"));
                txtS.setText(rs.getString("JenisBeras"));
                txtH.setText(rs.getString(4));
                txtB.setText(rs.getString(5));
                txtJ.setText(rs.getString(6));
                txtT.setText(rs.getString(7));
                txtD.setText(rs.getString(8));
                txtTH.setText(rs.getString(9));
                date.setDate(rs.getDate(10));
                JOptionPane.showMessageDialog(null, "Ini Data " + txtKB.getText() + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtKBActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btProsesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btProsesKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_btProsesKeyPressed

    private void btProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProsesActionPerformed
        a = Integer.parseInt(txtH.getText());
        b = Integer.parseInt(txtJ.getText());
        int t;
        Double j;
        Double d = 0.0;
        txtT.setText(String.valueOf(a * b));

        t = a * b;
        if (a > 3 || b > 7500000) {
            d = 0.1 * t;
        } else if (a < 3 || b < 7500000) {
            d = 0.0 * t;
        }

        j = t - d;

        txtD.setText(String.valueOf(d));
        txtTH.setText(String.valueOf(j));

        // TODO add your handling code here:
    }//GEN-LAST:event_btProsesActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed

        try {
            sql = "insert into tbbarang values ('"
            + txtKB.getText() + "','"
            + txtNB.getText() + "','"
            + txtS.getText() + "','"
            + txtH.getText() + "','"
            + txtB.getText() + "','"
            + txtJ.getText() + "','"
            + txtT.getText() + "','"
            + txtD.getText() + "','"
            + txtTH.getText() + "','"
            + tgl + "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data "+ txtKB.getText()+" Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data "+ txtKB.getText()+" Tidak Berhasil Disimpan");
        }

        txtKB.setText("");
        txtNB.setText("");
        txtS.setText("");
        txtH.setText("");
        txtB.setText("");
        txtJ.setText("");
        txtT.setText("");
        txtD.setText("");
        txtTH.setText("");
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed

        try {
            sql="update tbbarang set NamaBeras='"+
            txtNB.getText()+"',JenisBeras='"+
            txtS.getText()+"', harga='"+
            txtH.getText()+"',bonus='"+
            txtB.getText()+"',jumlah='"+
            txtJ.getText()+"', total='"+
            txtT.getText()+"',diskon='"+
            txtD.getText()+"',totalharga='"+
            txtTH.getText()+"', expired='"+
            tgl+"' where KodeBeras='"+txtKB.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data " + txtKB.getText() + "" + " Telah Di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + txtKB.getText() + "" + " Belum Di Edit"+e);
        }

        txtKB.setText("");
        txtNB.setText("");
        txtS.setText("");
        txtH.setText("");
        txtB.setText("");
        txtJ.setText("");
        txtT.setText("");
        txtD.setText("");
        txtTH.setText("");
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed

        try {
            sql = "delete from tbbarang where KodeBeras='" + txtKB.getText() + "'";
            stat = con.createStatement();
            stat.executeUpdate(sql);
            stat.close();
            JOptionPane.showMessageDialog(null, "Data " + txtKB.getText() + "" + " Telah Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + txtKB.getText() + "" + " Belum Dihapus");
        }

        txtKB.setText("");
        txtNB.setText("");
        txtS.setText("");
        txtH.setText("");
        txtB.setText("");
        txtJ.setText("");
        txtT.setText("");
        txtD.setText("");
        txtTH.setText("");
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed

        txtKB.setText("");
        txtNB.setText("");
        txtS.setText("");
        txtH.setText("");
        txtB.setText("");
        txtJ.setText("");
        txtT.setText("");
        txtD.setText("");
        txtTH.setText("");
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btBatalActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        txtKB.setText(jTable1.getValueAt
        (jTable1.getSelectedRow(), 0).toString());
        txtNB.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        txtS.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        txtH.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        txtB.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        txtJ.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        txtT.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        txtD.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        txtTH.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());

        String s =(String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 9);
        try {
            SimpleDateFormat f = new SimpleDateFormat("yyyy-M-dd");
            java.util.Date d = f.parse(s);
            date.setDate(d);
        } catch (Exception e) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuUtama().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    

    
    
    private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("Kode Beras");
        tabelmapel.addColumn("Nama Beras");
        tabelmapel.addColumn("JenisBeras");
        tabelmapel.addColumn("Harga");
        tabelmapel.addColumn("Bonus");
        tabelmapel.addColumn("Jumlah");
        tabelmapel.addColumn("Total");
        tabelmapel.addColumn("Diskon");
        tabelmapel.addColumn("Total Harga");
        tabelmapel.addColumn("Expired");
        try {
             sql = "select * from tbbarang";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("KodeBeras");
                o[1] = rs.getString("NamaBeras");
                o[2] = rs.getString("JenisBeras");
                o[3] = rs.getString("harga");
                o[4] = rs.getString("bonus");
                o[5] = rs.getString("jumlah");
                o[6] = rs.getString("total");
                o[7] = rs.getString("diskon");
                o[8] = rs.getString("totalharga");
                o[9] = rs.getString("expired");
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btProses;
    private javax.swing.JButton btSimpan;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtJ;
    private javax.swing.JTextField txtKB;
    private javax.swing.JTextField txtNB;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtT;
    private javax.swing.JTextField txtTH;
    // End of variables declaration//GEN-END:variables

    private Statement executeUpdate(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}

