/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Kel_4;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;

/**
 *
 * @author Administrator
 */
public class Pelanggan extends javax.swing.JFrame {
 public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
   
 
    /**
     * Creates new form 
     */
    public Pelanggan() {
        initComponents();
        setLocationRelativeTo(null);
        koneksiDB db = new koneksiDB();
        db.koneksi();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        np = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        btSimpan = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        no1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        np.setToolTipText("");
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        np.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                npKeyReleased(evt);
            }
        });
        getContentPane().add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 30));

        ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apActionPerformed(evt);
            }
        });
        ap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apKeyReleased(evt);
            }
        });
        getContentPane().add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 30));

        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, 30));

        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noKeyReleased(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 30));

        btSimpan.setBackground(new java.awt.Color(84, 93, 102));
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-save-as.png"))); // NOI18N
        btSimpan.setText("SIMPAN");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        btEdit.setBackground(new java.awt.Color(84, 93, 102));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-edit.png"))); // NOI18N
        btEdit.setText("EDIT");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 100, -1));

        btDelete.setBackground(new java.awt.Color(84, 93, 102));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/document_delete.png"))); // NOI18N
        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 100, -1));

        btBatal.setBackground(new java.awt.Color(84, 93, 102));
        btBatal.setText("CLEAR");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 100, 36));

        btKeluar.setBackground(new java.awt.Color(84, 93, 102));
        btKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/1382877036_Exit.png"))); // NOI18N
        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 340, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 790, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAMA PELANGGAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALAMAT PELANGGAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMAIL PELANGGAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMOR HP PELANGGAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jButton1.setBackground(new java.awt.Color(84, 93, 102));
        jButton1.setText("Menu Utama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 780, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/ss.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 480, -1));

        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });
        no1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no1KeyReleased(evt);
            }
        });
        getContentPane().add(no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Keterangan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/hero-product-pages.jpg"))); // NOI18N
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1030, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed

        try {
            sql = "select * from tblpelanggan where namapelanggan='" + np.getText() + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                ap.setText(rs.getString("namapelanggan"));
                mail.setText(rs.getString("email"));
                no.setText(rs.getString(4));
               
                JOptionPane.showMessageDialog(null, "Ini Data " + np.getText() + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void npKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npKeyReleased

        if (evt.getKeyCode() == 10) {
            ap.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_npKeyReleased

    private void apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apActionPerformed

    private void apKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apKeyReleased

        if (evt.getKeyCode() == 10) {
            mail.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_apKeyReleased

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased

        if (evt.getKeyCode() == 10) {
            no.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyReleased

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyReleased

        if (evt.getKeyCode() == 10) {
            np.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_noKeyReleased

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed

        try {
            sql = "insert into  tblpelanggan values ('"
            + np.getText() + "','"
            + ap.getText() + "','"
            + mail.getText() + "','"
            + no.getText() + "','"
            +no1.getText() + "')";
         
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data "+ np.getText()+" Berhasil Disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data "+ np.getText()+" Tidak Berhasil Disimpan"+e);
        }

        np.setText("");
        ap.setText("");
        mail.setText("");
        no.setText("");
       no1.setText("");

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed

        try {
            sql="update tblpelanggan set alamat='"+
            ap.getText()+"',email='"+
            mail.getText()+"', nomorhp='"+
            no.getText()+"', ket='"+
                    no1.getText()
       
            +"' where namapelanggan='"+np.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data " + np.getText() + "" + " Telah Di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + np.getText() + "" + " Belum Di Edit"+e);
        }

        np.setText("");
        ap.setText("");
        mail.setText("");
        no.setText("");
         no1.setText("");
     
   

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed

        try {
            sql = "delete from tblpelanggan where namapelanggan='" + np.getText() + "'";
            stat = con.createStatement();
            stat.executeUpdate(sql);
            stat.close();
            JOptionPane.showMessageDialog(null, "Data " + np.getText() + "" + " Telah Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + np.getText() + "" + " Belum Dihapus");
        }

        np.setText("");
        ap.setText("");
        mail.setText("");
        no.setText("");
         no1.setText("");
    

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed

        np.setText("");
        ap.setText("");
        mail.setText("");
        no.setText("");
         no1.setText("");
        

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btBatalActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btKeluarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        np.setText(jTable1.getValueAt
            (jTable1.getSelectedRow(), 0).toString());
        ap.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        mail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        no.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
     

     

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no1ActionPerformed

    private void no1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_no1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuUtama().show();
    }//GEN-LAST:event_jButton1ActionPerformed
  private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("Nama Pelanggan");
        tabelmapel.addColumn("alamat");
        tabelmapel.addColumn("email");
        tabelmapel.addColumn("Nomor HP");
        tabelmapel.addColumn("Keterangan");
        try {
             sql = "select * from tblpelanggan";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[5];
                o[0] = rs.getString("namapelanggan");
                o[1] = rs.getString("alamat");
                o[2] = rs.getString("email");
                o[3] = rs.getString("nomorhp");
              o[4] = rs.getString("ket");
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ap;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField no;
    private javax.swing.JTextField no1;
    private javax.swing.JTextField np;
    // End of variables declaration//GEN-END:variables

}