/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Kel_4;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;
/**
 *
 * @author Administrator
 */
public class penjualan extends javax.swing.JFrame {
 public Connection con;
    public Statement stat;
    public ResultSet rs;
    public String sql = "";
    public String tgl = "";
    public String KodeBeras = "";
    Integer a, b, hasil;
    /**
     * Creates new form 
     */
    public penjualan() {
          initComponents();
        setLocationRelativeTo(null);
        koneksiDB db = new koneksiDB();
        db.koneksi();
        con = db.con;
        stat = db.stat;
        tampilkan_data();
    }
    
    private void atur(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        IDPen = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JJ = new javax.swing.JTextField();
        TOT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KB = new javax.swing.JTextField();
        NB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        H = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JML = new javax.swing.JTextField();
        IDPel = new javax.swing.JTextField();
        IDP1 = new javax.swing.JLabel();
        NP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSimpan = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("ID Penjualan");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        IDPen.setToolTipText("");
        IDPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPenActionPerformed(evt);
            }
        });
        IDPen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IDPenKeyReleased(evt);
            }
        });
        getContentPane().add(IDPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 30));

        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 30));

        jLabel7.setText("EXPIRED");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel11.setText("JUMLAH Jual");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel10.setText("TOTAL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        JJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JJActionPerformed(evt);
            }
        });
        JJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JJKeyReleased(evt);
            }
        });
        getContentPane().add(JJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, 30));

        TOT.setEditable(false);
        TOT.setBackground(new java.awt.Color(255, 255, 255));
        TOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTActionPerformed(evt);
            }
        });
        getContentPane().add(TOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, 30));

        jLabel2.setText("KODE BERAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel3.setText("NAMA BERAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        KB.setToolTipText("");
        KB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KBActionPerformed(evt);
            }
        });
        KB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KBKeyReleased(evt);
            }
        });
        getContentPane().add(KB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 140, 30));

        NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NBActionPerformed(evt);
            }
        });
        NB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NBKeyReleased(evt);
            }
        });
        getContentPane().add(NB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 140, 30));

        jLabel5.setText("HARGA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        H.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HKeyReleased(evt);
            }
        });
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 140, 30));

        jLabel12.setText("JUMLAH");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        JML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMLActionPerformed(evt);
            }
        });
        JML.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JMLKeyReleased(evt);
            }
        });
        getContentPane().add(JML, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 140, 30));

        IDPel.setToolTipText("");
        IDPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPelActionPerformed(evt);
            }
        });
        IDPel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IDPelKeyReleased(evt);
            }
        });
        getContentPane().add(IDPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 140, 30));

        IDP1.setText("ID Pelanggan");
        getContentPane().add(IDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 80, -1));

        NP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPActionPerformed(evt);
            }
        });
        NP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NPKeyReleased(evt);
            }
        });
        getContentPane().add(NP, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 140, 30));

        jLabel4.setText("NAMA Pelanggan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 950, 100));

        btSimpan.setBackground(new java.awt.Color(84, 93, 102));
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-save-as.png"))); // NOI18N
        btSimpan.setText("SIMPAN");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, -1));

        btEdit.setBackground(new java.awt.Color(84, 93, 102));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/gtk-edit.png"))); // NOI18N
        btEdit.setText("EDIT");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 140, -1));

        btBatal.setBackground(new java.awt.Color(84, 93, 102));
        btBatal.setText("CLEAR");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 190, 36));

        btKeluar.setBackground(new java.awt.Color(84, 93, 102));
        btKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/1382877036_Exit.png"))); // NOI18N
        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 290, -1));

        jButton1.setBackground(new java.awt.Color(84, 93, 102));
        jButton1.setText("Menu Utama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 950, 40));

        btDelete.setBackground(new java.awt.Color(84, 93, 102));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory_Kel_4/document_delete.png"))); // NOI18N
        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPenActionPerformed

        

        // TODO add your handling code here:
    }//GEN-LAST:event_IDPenActionPerformed

    private void IDPenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDPenKeyReleased

        if (evt.getKeyCode() == 10) {
            NB.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_IDPenKeyReleased

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange

        if (date.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            tgl = String.valueOf(format.format(date.getDate()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_datePropertyChange

    private void JJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JJActionPerformed

    private void JJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JJKeyReleased

       // if (evt.getKeyCode() == 10) {
         //   btProses.requestFocus();
        //}

        // TODO add your handling code here:
    }//GEN-LAST:event_JJKeyReleased

    private void TOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TOTActionPerformed

    private void KBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KBActionPerformed

        try {
            sql = "select * from tbbarang where KodeBeras='" + KB.getText() + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                NB.setText(rs.getString("NamaBeras"));
                H.setText(rs.getString("harga"));
                JML.setText(rs.getString(6));
         
                date.setDate(rs.getDate(10));
                JOptionPane.showMessageDialog(null, "Ini Data " + KB.getText() + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_KBActionPerformed

    private void KBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KBKeyReleased

        if (evt.getKeyCode() == 10) {
            NB.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_KBKeyReleased

    private void NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NBActionPerformed

    private void NBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NBKeyReleased

      

        // TODO add your handling code here:
    }//GEN-LAST:event_NBKeyReleased

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HActionPerformed

    private void HKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HKeyReleased

      
        // TODO add your handling code here:
    }//GEN-LAST:event_HKeyReleased

    private void JMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMLActionPerformed

    private void JMLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JMLKeyReleased

    
        // TODO add your handling code here:
    }//GEN-LAST:event_JMLKeyReleased

    private void IDPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPelActionPerformed

    private void IDPelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDPelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPelKeyReleased

    private void NPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NPActionPerformed

    private void NPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_NPKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        KB.setText(jTable1.getValueAt
            (jTable1.getSelectedRow(), 0).toString());
        NB.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
    
        H.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());

        JJ.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        TOT.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
      

        String s =(String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 9);
        try {
            SimpleDateFormat f = new SimpleDateFormat("yyyy-M-dd");
            java.util.Date d = f.parse(s);
            date.setDate(d);
        } catch (Exception e) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed

        try {
            sql = "insert into tblpenjualan values ('"
            + KB.getText() + "','"
            + NB.getText() + "','"
            + H.getText() + "','"
            + JML.getText() + "','"
            + JJ.getText() + "','"
            + TOT.getText() + "','"
            + IDPel.getText() + "','"
            + NP.getText() + "','"
            + tgl + "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data "+ KB.getText()+" Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data "+ KB.getText()+" Tidak Berhasil Disimpan");
        }

        KB.setText("");
        NB.setText("");
        H.setText("");
        JML.setText("");
        JJ.setText("");
        TOT.setText("");
        IDPel.setText("");
        NP.setText("");
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed

        try {
            sql="update tbbarang set NamaBeras='"+
            NB.getText()+"',JenisBeras='"+
            H.getText()+"', harga='"+
            JML.getText()+"',bonus='"+
            JJ.getText()+"',jumlah='"+
            TOT.getText()+"', total='"+
            IDPel.getText()+"',diskon='"+
            tgl+"' where KodeBeras='"+KB.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data " + KB.getText() + "" + " Telah Di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " + KB.getText() + "" + " Belum Di Edit"+e);
        }

        KB.setText("");
        NB.setText("");
        
        H.setText("");
      
        JJ.setText("");
        TOT.setText("");
   
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed

        KB.setText("");
        NB.setText("");
  
        H.setText("");
      
        JJ.setText("");
        TOT.setText("");
     
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btBatalActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btKeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuUtama().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed

        try {
            sql = "delete from tbbarang where KodeBeras='" + KB.getText() + "'";
            stat = con.createStatement();
            stat.executeUpdate(sql);
            stat.close();
            JOptionPane.showMessageDialog(null, "Data " + KB.getText() + "" + " Telah Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data " +KB.getText() + "" + " Belum Dihapus");
        }

        KB.setText("");
        NB.setText("");
      
        H.setText("");
      
        JJ.setText("");
        TOT.setText("");
      
     
        date.setDate(null);

        tampilkan_data();

        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

     private void tampilkan_data() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("Kode Beras");
        tabelmapel.addColumn("Nama Beras");
        tabelmapel.addColumn("JenisBeras");
        tabelmapel.addColumn("Harga");
        tabelmapel.addColumn("Bonus");
        tabelmapel.addColumn("Jumlah");
        tabelmapel.addColumn("Total");
        tabelmapel.addColumn("Diskon");
        tabelmapel.addColumn("Total Harga");
        tabelmapel.addColumn("Expired");
        try {
             sql = "select * from tbbarang";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[10];
                o[0] = rs.getString("KodeBeras");
                o[1] = rs.getString("NamaBeras");
                o[2] = rs.getString("JenisBeras");
                o[3] = rs.getString("harga");
                o[4] = rs.getString("bonus");
                o[5] = rs.getString("jumlah");
                o[6] = rs.getString("total");
                o[7] = rs.getString("diskon");
                o[8] = rs.getString("totalharga");
                o[9] = rs.getString("expired");
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField H;
    private javax.swing.JLabel IDP1;
    private javax.swing.JTextField IDPel;
    private javax.swing.JTextField IDPen;
    private javax.swing.JTextField JJ;
    private javax.swing.JTextField JML;
    private javax.swing.JTextField KB;
    private javax.swing.JTextField NB;
    private javax.swing.JTextField NP;
    private javax.swing.JTextField TOT;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btSimpan;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    // End of variables declaration//GEN-END:variables
}
